### PR TITLE
[EN TH] Datomic keys

### PR DESCRIPTION
**Pull request by ericnormand**
Add a lein deps script that lets lein deps pull down datomic.

Does NOT store any datomic credentials in the container.

### CODE REVIEW

**Comment by ericnormand** [comment]
Assigned to @cap10morgan

**Comment by cap10morgan** [comment]
We've solved this problem using profiles.clj in other projects (see ballot-scout kraken branch for example).

But why would the buildkite agent need access to these?

**Comment by ericnormand** [comment]
Where does the ballot-scout buildkite get them from when running script/build?

**Comment by cap10morgan** [comment]
@ericnormand You have to create it by copying `profiles.clj.sample` to `profiles.clj` and putting your My Datomic username and download key into `profiles.clj`. That's been added to the README in the [misc-improvements branch](https://github.com/democracyworks/ballot-scout/pull/115).

The build script then copies `profiles.clj` into the Docker image along with `project.clj` before running `lein deps`. So the credentials are baked into the Docker image, but we need private repos anyway since they contain software we're not allowed to redistribute.

**Comment by ericnormand** [comment]
That's not what I'm asking. Where does Buildkite, the CI server, get that from?

**Comment by cap10morgan** [comment]
@ericnormand Ah, sorry. I misunderstood your question.

It gets them from BuildKite project env vars and [the build script writes them to a profiles.clj](https://github.com/democracyworks/ballot-scout/blob/kraken/script/build#L7-L10).

**Pull request closed without merging**
